### ISSUE TITLE
Posters for September

### ISSUE THREAD

**Issue by ct-martin** [RITlug/brand#4]
Design has been approved by Campus Life; would like to get up before meeting on Friday. We have 200 free BW copies from campus life and RHA will put up the posters on dorm side, so how many do we want?

**Comment by justwheel** [comment]
@ct-martin Do you know if the 200 posters are per academic year or per semester?

**Comment by ct-martin** [comment]
Academic year

--
Christian Martin

**Comment by jibby0** [comment]
Since we have to submit the EAF and wait 1 business day for free prints, I'll prolly just dip into the 500 I have for the semester for RIT, and run some off tomorrow. That way they'll be up a day before our first meeting. Is that alright?
As far as quantity goes, @ct-martin you said we give them to reslife for them to put up in the dorms, right? We can't put them up ourselves? How many academic buildings do we want to hit (GCCIS, likely the engineering building, the science building, the business building)? How many should each building have, appropximately?
Also, who's gonna put them up? I have tape, and don't mind, but more hands is always nice.

**Comment by ct-martin** [comment]
The new rules are linked somewhere in Slack; I don't have the ability to
dig it up right now. We also need painter's tape, we need them stamped by
club office, and there are certain places we can't put them now too.

--
Christian Martin (Phone)

**Comment by jibby0** [comment]
This? https://www.rit.edu/studentaffairs/fsl/sites/rit.edu.studentaffairs.fsl/files/files/images/Posting%20Procedures_Revised%2012.01.2016.pdf

True, we'd be limited to res halls. I can pick up painters tape if need be.

Also relevant:
Club fliers/posters need to be approved via email by the Senior Associate Director, Shawna Lusk (shawna.lusk@rit.edu).

Does that differ from the Campus Life approval?

**Comment by ct-martin** [comment]
The approval should have been covered by the CampusGroups form. We can post
on academic side, but I don't remember what the quirks are.

--
Christian Martin (Phone)

**Comment by ct-martin** [comment]
Also not able to check the PDF at the moment, but the link looks correct

--
Christian Martin (Phone)

**Comment by justwheel** [comment]
> _**@ct-martin said…**_
> The approval should have been covered by the CampusGroups form.

Were the posters already approved?

> _**@jibby0 said…**_
> Since we have to submit the EAF and wait 1 business day for free prints, I'll prolly just dip into the 500 I have for the semester for RIT, and run some off tomorrow. That way they'll be up a day before our first meeting. Is that alright?

If the design is approved, printing some off and getting a small number posted can't hurt. We don't have to be overly ambitious but we can get some done.

> _**@jibby0 said…**_
>  Also, who's gonna put them up? I have tape, and don't mind, but more hands is always nice.

If someone has painter's tape I can borrow, I can commit to hanging 15 posters in GCCIS today. I am not on campus for long on Thursdays, or else I would try to do more.

**Comment by jibby0** [comment]
Ive got a few rolls of painters tape. @jwflory lmk when you're on campus and I can give you a roll.
I can throw 20-30 up in res halls today.

**Comment by ct-martin** [comment]
Campus Life has the stamp for posters and painter's tape. It's been
approved so it should be really quick

--
Christian Martin (Phone)

**Comment by jibby0** [comment]
Does that mean we can start putting them up now, or no?

**Comment by ct-martin** [comment]
It means you go to club office, give them the posters, say they've been
approved online already, and they will stamp them. Then put them up

--
Christian Martin (Phone)

**Comment by justwheel** [comment]
@jibby0 Not sure if you had a chance to get any up yesterday – I missed the email for this.

I think our best strategy is to work with Clubs Office this week to see if we can have them hang printed posters from our yearly allowance. For that, I suggest closing this issue and opening it in the **tasks** repository.

**Comment by ct-martin** [comment]
Club office does not hang posters. Please read the new guidelines linked
both here and Slack

--
Christian Martin (Phone)

**Comment by justwheel** [comment]
Since September is nearly over, it wouldn't make much sense to hang posters now. I'm closing this for now, and we can plan for October better (probably part of the discussion in RITlug/tasks#63).
